services:
  surreal:
    container_name: agora-surreal
    image: docker.io/surrealdb/surrealdb:nightly
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - dbdata:/data/surreal
    security_opt:
      label: disable
    environment:
      - BIND=${SURREAL_BIND}
      - DB_PATH=${SURREAL_DB_PATH}
      - USER=${SURREAL_USER}
      - PASS=${SURREAL_PASS}
      - LOG=${SURREAL_LOG}
    command: ["start"]

volumes:
  dbdata:
