services:
  surreal:
    container_name: agora-surreal
    image: docker.io/surrealdb/surrealdb:1.0.0-beta.9-20230402
    restart: on-failure
    volumes:
      - dbdata:/data/surreal
    security_opt:
      label: disable
    env_file:
      - .env
    command: ["start"]

  rabbitmq:
    container_name: agora-rabbitmq
    image: docker.io/rabbitmq:3.10.2-alpine
    hostname: agora-rabbitmq
    restart: always
    security_opt:
      label: disable

  grpc:
    container_name: agora-grpc
    image: localhost/alvidir/agora:latest-grpc
    restart: always
    volumes:
      - ./templates:/etc/agora/smtp/templates:ro
    security_opt:
      label: disable
    depends_on:
      - surreal
      - rabbitmq
    env_file:
      - .env
    environment:
      - SERVICE_PORT=8000

  envoy:
    container_name: agora-envoy
    image: docker.io/envoyproxy/envoy-alpine:v1.21-latest
    restart: always
    volumes:
      - ./envoy:/etc/envoy:ro
    security_opt:
      label: disable
    depends_on:
      - grpc
    command: /usr/local/bin/envoy --log-level debug -c /etc/envoy/envoy.yaml

  nginx:
    container_name: agora-nginx
    image: docker.io/nginx:1.23.2-alpine
    restart: always
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    security_opt:
        label: disable
    depends_on:
      - envoy

volumes:
  dbdata:
