version: '3.9'

services:
  zero:
    container_name: zero
    image: docker.io/dgraph/dgraph:latest
    volumes:
      - zero-data:/dgraph
    networks:
      - dgraph
    restart: on-failure
    command: dgraph zero --my=zero:5080

  alpha:
    container_name: alpha
    image: docker.io/dgraph/dgraph:latest
    volumes:
      - alpha-data:/dgraph
    ports:
      - 8080:8080
    restart: on-failure
    command: dgraph alpha --security whitelist=10.0.2.100 --my=alpha:7080 --zero=zero:5080 

  ratel:
    container_name: ratel
    image: docker.io/dgraph/ratel:latest
    ports:
      - 8000:8000
    networks:
      - dgraph

networks:
    # dgraph network is the bridge between domain environment and dgraph service
    dgraph:
        name: dgraph
        driver: bridge

volumes:
  zero-data:
  alpha-data:
